Vagrant.configure("2") do |web|
    web.vm.box = "generic/ubuntu2204"
    web.vm.hostname = "web"

    web.vm.synced_folder ".", "/vagrant"
    web.vm.network "forwarded_port", guest: 8080, host: 8080

    web.vm.provision "shell", inline: <<-SHELL
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
    SHELL
  end