Vagrant.configure("2") do |config|
  # Настройка машины backup
  config.vm.define "backup" do |backup|
    backup.vm.box = "generic/ubuntu2204"
    backup.vm.hostname = "backup"
    backup.vm.network "private_network", ip: "192.168.50.13"

    backup.vm.provider "virtualbox" do |vb|
      vb.customize ["createhd", "--filename", "backup_disk.vdi", "--size", 2048] 
      vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 1, "--device", 0, "--type", "hdd", "--medium", "backup_disk.vdi"]
    end
  end

  # Настройка машины client
  config.vm.define "client" do |client|
    client.vm.box = "generic/ubuntu2204"
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.50.14"
  end
end