Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.hostname = "bash"
    config.vm.synced_folder ".", "/vagrant"
  
    # config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    #
    #   # Customize the amount of memory on the VM:
    #   vb.memory = "1024"
    # end
  
    config.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      apt update
      debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Local Only'"
      apt install -y mailutils
      adduser vagrant mail
      touch /var/mail/vagrant
      sudo chown vagrant:mail /var/mail/vagrant && chmod 660 /var/mail/vagrant
      echo "0 * * * * /vagrant/script.sh" > /var/spool/cron/crontabs/vagrant
    SHELL
  end
  