Vagrant.configure("2") do |config|
    # Настройка машины web
    config.vm.define "web" do |web|
      web.vm.box = "generic/ubuntu2204"
      web.vm.hostname = "web"
      web.vm.network "private_network", ip: "192.168.50.13"
      web.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y nginx
        systemctl enable nginx
        systemctl start nginx
      SHELL
    end
  
    # Настройка машины log
    config.vm.define "log" do |log|
      log.vm.box = "generic/ubuntu2204"
      log.vm.hostname = "log"
      log.vm.network "private_network", ip: "192.168.50.14"
      log.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y rsyslog
        systemctl enable rsyslog
        systemctl start rsyslog
      SHELL
    end
  end